import type { ProductionSheet } from "./schema";
import { detectSafety } from "./safety";
import { detectAllergens } from "./validate";

/**
 * HACCP / CCP summary (master prompt Module 3, output per Module 19).
 * Built DETERMINISTICALLY from the finished production sheet: hazards are
 * detected from the ingredients/method/mode, and every critical limit is an
 * FDA Food Code number (the same ones the safety layer quotes) — never
 * generated by the model. Distinguishes CCP / CP / QCP so not every prep step
 * is labeled a CCP.
 */

export type ControlKind = "CCP" | "CP" | "QCP";
export type ControlEntry = {
  step: string;
  kind: ControlKind;
  hazard: string;
  limit: string;
  monitor: string;
  corrective: string;
  verify: string;
  record: string;
};
export type HaccpPlan = { dish: string; covers: number; entries: ControlEntry[]; notes: string[] };

export const KIND_MEANING: Record<ControlKind, string> = {
  CCP: "critical control point — control here is essential to prevent or eliminate a food-safety hazard",
  CP: "control point — manages a hazard but is not the last line of defense",
  QCP: "quality control point — protects quality, not safety",
};

type ProteinClass = "poultry" | "stuffed" | "ground" | "whole" | "fish" | "shellfish" | "egg";

const PROTEIN: Record<ProteinClass, RegExp> = {
  poultry: /\b(chicken|turkey|duck|poultry|hen|goose)\b/,
  stuffed: /\b(stuffed|stuffing)\b/,
  ground: /\b(ground|minced)\s+(beef|pork|turkey|chicken|lamb|meat|veal)\b|\b(sausage|chorizo|burger|meatball|meatloaf|kofta|kebab)\b/,
  whole: /\b(beef|steak|sirloin|chuck|brisket|flank|skirt|carne|pork|pernil|ham|lamb|roast|chops?|loin|tenderloin|ribs?|veal|bacon)\b/,
  fish: /\b(fish|salmon|cod|tuna|tilapia|halibut|snapper|trout|mahi|ceviche|anchov\w*)\b/,
  shellfish: /\b(shrimp|prawns?|crab|lobster|mussels?|clams?|oysters?|scallops?|squid|calamari)\b/,
  egg: /\beggs?\b/,
};

const TCS = /\b(milk|cream|cheese|yogurt|butter|paneer|tofu|rice|beans?|lentils?|pasta|noodles?|potato|diced|chopped|sliced|cut|melon|sprouts?|greens|lettuce)\b/;

function sheetText(sheet: ProductionSheet): string {
  return [
    sheet.dish,
    sheet.mode,
    ...sheet.ingredients.map((i) => i.item),
    ...sheet.method,
    ...sheet.holding,
    ...sheet.safetyFlags,
    ...sheet.assumptions,
  ]
    .join(" \n ")
    .toLowerCase();
}

/** Governing cook limit: strictest class present wins. */
function cookLimit(classes: ProteinClass[]): { limit: string; governing: string; also: string[] } {
  const has = (c: ProteinClass) => classes.includes(c);
  const also: string[] = [];
  if (has("ground")) also.push("ground meat 155°F (68°C), 17 s");
  if (has("whole") || has("fish") || has("shellfish") || has("egg")) also.push("whole-muscle meat / fish / eggs 145°F (63°C), 15 s");
  if (has("poultry") || has("stuffed")) {
    return { limit: "165°F (74°C) internal, 15 s", governing: has("stuffed") && !has("poultry") ? "stuffed item" : "poultry", also };
  }
  if (has("ground")) {
    return { limit: "155°F (68°C) internal, 17 s", governing: "ground meat", also: also.slice(1) };
  }
  if (has("whole") || has("fish") || has("shellfish") || has("egg")) {
    return { limit: "145°F (63°C) internal, 15 s", governing: has("fish") || has("shellfish") ? "fish / seafood" : has("egg") ? "eggs" : "whole-muscle meat", also: [] };
  }
  return { limit: "135°F (57°C) for hot holding (plant / ready-to-eat)", governing: "plant-based, hot-held", also: [] };
}

export function buildHaccp(sheet: ProductionSheet): HaccpPlan {
  const t = sheetText(sheet);
  const classes = (Object.keys(PROTEIN) as ProteinClass[]).filter((c) => PROTEIN[c].test(t));
  const rawAnimal = classes.length > 0;
  const tcs = rawAnimal || TCS.test(t);
  const allergens = detectAllergens(sheet.ingredients.map((i) => i.item).join(" ").toLowerCase());
  const domains = new Set(detectSafety(t).map((r) => r.domain));
  if (sheet.mode === "safety_chemistry" && domains.size === 0) domains.add("brine/cure");
  const rice = /\brice\b/.test(t);

  const e: ControlEntry[] = [];

  e.push({
    step: "Receiving",
    kind: "CP",
    hazard: "Pathogens or temperature abuse on delivery; unapproved sources.",
    limit: "Approved suppliers only. Cold TCS foods ≤41°F (5°C) on receipt; frozen goods frozen solid; shellfish with tags.",
    monitor: "Probe TCS deliveries at the door; check packaging, dates, and tags.",
    corrective: "Reject out-of-temp or damaged product and note the rejection.",
    verify: "Manager reviews the receiving log weekly; supplier approvals on file.",
    record: "Receiving log (date, item, temp, accept/reject).",
  });

  e.push({
    step: "Cold storage & cold holding",
    kind: tcs ? "CCP" : "CP",
    hazard: tcs ? "Pathogen growth in TCS ingredients during storage." : "Spoilage; no TCS ingredients detected on this sheet.",
    limit: "≤41°F (5°C). Raw animal proteins stored below ready-to-eat foods, shelved by cook temperature (poultry lowest).",
    monitor: "Unit thermometers checked at start and end of shift; product probed at prep.",
    corrective: "If >41°F: time out of temp <4 h → use immediately or chill; unknown or >4 h → discard. Service the unit.",
    verify: "Unit thermometers calibrated; log reviewed daily.",
    record: "Cold-holding temperature log.",
  });

  e.push({
    step: "Prep & cross-contamination",
    kind: "CP",
    hazard: rawAnimal
      ? "Cross-contamination from raw proteins to ready-to-eat items; hand contact."
      : "Cross-contamination from soiled surfaces and hands; bare-hand contact with ready-to-eat food.",
    limit: "Separate color-coded boards/utensils for raw and RTE; sanitizer at label concentration; hands washed between tasks; no bare-hand contact with RTE food.",
    monitor: "Line lead checks station setup at start of prep; sanitizer test strips each shift.",
    corrective: "Re-sanitize surfaces; discard RTE food that contacted raw juices; re-train.",
    verify: "Sanitizer strip readings logged; chef spot checks.",
    record: "Sanitizer log; cleaning schedule.",
  });

  if (allergens.length > 0) {
    e.push({
      step: "Allergen control",
      kind: "CP",
      hazard: `Allergen cross-contact — ${allergens.join(", ")} present in this recipe.`,
      limit: "Dedicated utensils/pans for allergen-free items; accurate labeling at service; posted allergen info matches the recipe as made.",
      monitor: "Label check before service; recipe changes reviewed against the allergen matrix.",
      corrective: "Pull mislabeled product; remake affected items with clean equipment; notify service.",
      verify: "Allergen matrix updated on every recipe change; manager sign-off.",
      record: "Allergen matrix / label-check log.",
    });
  }

  if (domains.has("brine/cure")) {
    e.push({
      step: "Cure / brine concentration",
      kind: "CCP",
      hazard: "Nitrite toxicity or C. botulinum if the cure or salt concentration is wrong.",
      limit: "Cure and salt scaled LINEARLY with the water and meat to the exact validated ratio; nitrite per a validated cure calculator (USDA FSIS limits).",
      monitor: "Weigh cure and salt on a calibrated scale each batch; second-person check.",
      corrective: "Ratio off → remake the brine; discard product cured with the wrong dose.",
      verify: "Validated cure calculation on file; scale calibrated.",
      record: "Cure batch sheet (weights, initials).",
    });
  }

  const cook = cookLimit(classes);
  e.push({
    step: "Cooking",
    kind: "CCP",
    hazard: rawAnimal
      ? "Survival of pathogens (Salmonella, Campylobacter, E. coli O157, etc.) if undercooked."
      : "Survival of pathogens on plant foods that will be hot-held.",
    limit: `${cook.limit} — governs because of ${cook.governing}.${cook.also.length ? ` Also present: ${cook.also.join("; ")}.` : ""}`,
    monitor: "Probe the thickest part of every batch and every pan with a calibrated thermometer.",
    corrective: "Continue cooking until the limit is met; never serve or hold below it.",
    verify: "Thermometer ice-point calibration daily; chef reviews the cook log each service.",
    record: "Cooking temperature log (batch, time, temp, initials).",
  });

  if (domains.has("pickling/canning")) {
    e.push({
      step: "Acidification / pH",
      kind: "CCP",
      hazard: "C. botulinum in low-acid, sealed or anaerobic product.",
      limit: "Equilibrium pH ≤4.6 per a tested (NCHFP) recipe — never reduce acid for flavor; otherwise pressure-can or keep refrigerated as a TCS food.",
      monitor: "Calibrated pH meter on each batch (strips acceptable for refrigerated pickles).",
      corrective: "pH >4.6 → add acid per the validated recipe and re-test, or refrigerate and treat as TCS.",
      verify: "Tested recipe / process authority letter on file; meter calibrated with buffers.",
      record: "pH log per batch.",
    });
  }

  if (domains.has("sous-vide")) {
    e.push({
      step: "Reduced-oxygen / sous vide",
      kind: "CCP",
      hazard: "C. botulinum and pathogen survival in reduced-oxygen, low-temperature cooking.",
      limit: "Time–temperature from a validated, thickness-based pasteurization table — never improvised. ROP requires a HACCP plan / variance under the FDA Food Code.",
      monitor: "Bath temperature and time logged per batch; core temperature verified.",
      corrective: "Bath or time short → extend to the validated time or finish conventionally to the standard limit; discard if unknown.",
      verify: "Validated table cited on the recipe; circulator calibrated.",
      record: "Sous-vide time/temperature log.",
    });
  }

  if (domains.has("garlic-in-oil")) {
    e.push({
      step: "Garlic / herb in oil",
      kind: "CCP",
      hazard: "C. botulinum — low-acid garlic or herbs in oil (anaerobic).",
      limit: "Refrigerate ≤41°F (5°C); use within 3–4 days or freeze; never hold at room temperature.",
      monitor: "Date-label at make; check dates at each service.",
      corrective: "Discard undated, out-of-date, or room-temperature product.",
      verify: "Chef checks labels daily.",
      record: "Date labels; discard log.",
    });
  }

  if (domains.has("fermentation")) {
    e.push({
      step: "Fermentation",
      kind: "CCP",
      hazard: "Pathogen growth if the salt ratio or pH is not controlled.",
      limit: "Exact salt-by-weight ratio from a validated recipe; pH ≤4.6 before serving, or keep refrigerated.",
      monitor: "Salt weighed per batch; pH checked before service.",
      corrective: "Below target salt or above target pH → discard or restart per the validated recipe.",
      verify: "Validated ratio on file; pH meter calibrated.",
      record: "Fermentation log (salt %, pH, dates).",
    });
  }

  e.push({
    step: "Hot holding",
    kind: "CCP",
    hazard: "Pathogen growth in the danger zone (41–135°F) on the line.",
    limit: "≥135°F (57°C) in every pan.",
    monitor: "Probe every pan at set-up and at least every 2 h; stir and rotate pans.",
    corrective: "Below 135°F → if time out of temp is known and <2 h, reheat rapidly to 165°F (74°C) and return; otherwise discard.",
    verify: "Hot-hold log reviewed each service; thermometer calibration.",
    record: "Hot-holding temperature log (pan, time, temp).",
  });

  e.push({
    step: "Cooling (cook-ahead / leftovers)",
    kind: "CCP",
    hazard: `Spore-formers (C. perfringens${rice ? ", B. cereus in cooked rice" : ", B. cereus"}) grow in slow-cooled, dense food.`,
    limit: "135→70°F (57→21°C) within 2 h, then 70→41°F (21→5°C) within 4 more h (≤6 h total).",
    monitor: "Shallow pans ≤2 in deep, vented; probe at 2 h and at 6 h.",
    corrective: "Miss 70°F at 2 h → reheat to 165°F and restart cooling once; miss 41°F at 6 h → discard.",
    verify: "Cooling log reviewed daily; pan depth checked.",
    record: "Cooling log (start temp/time, 2 h, 6 h).",
  });

  e.push({
    step: "Reheating (leftovers / cook-chill)",
    kind: "CCP",
    hazard: "Pathogen survival if reheated slowly or below temperature.",
    limit: "≥165°F (74°C) within 2 h before hot holding.",
    monitor: "Probe each batch after reheating.",
    corrective: "Continue reheating to 165°F; discard if the 2 h window is exceeded.",
    verify: "Reheating log reviewed.",
    record: "Reheating log.",
  });

  e.push({
    step: "Hot-line quality hold",
    kind: "QCP",
    hazard: "Quality loss, not a safety hazard — starch absorption, sauces tightening, seasoning drift, herbs wilting.",
    limit: "Hold each pan ≤90 min; refresh from the line; finish herbs and crisp items at the pass.",
    monitor: "Pan timers or time-in labels.",
    corrective: "Swap tired pans for fresh; loosen with reserved stock; correct seasoning.",
    verify: "Chef tastes the line each service.",
    record: "Line refresh log (optional).",
  });

  const detected = [
    ...classes.map((c) => (c === "whole" ? "whole-muscle meat" : c)),
    ...[...domains].map((d) => `${d} prep`),
    ...(allergens.length ? [`allergens: ${allergens.join(", ")}`] : []),
  ];

  return {
    dish: sheet.dish,
    covers: sheet.targetYield.covers,
    entries: e,
    notes: [
      `Detected on this sheet: ${detected.length ? detected.join(" · ") : "no raw animal proteins or special preps"}.`,
      "Critical limits are FDA Food Code numbers. This summary supports your operation's HACCP plan — it does not replace it. Verify against your plan and local health code.",
    ],
  };
}

/** Copy-code format (Module 19): clean, copyable, ready for real use. */
export function haccpText(plan: HaccpPlan): string {
  const lines: string[] = [
    `HACCP / CCP SUMMARY — ${plan.dish} (${plan.covers} covers)`,
    "=".repeat(50),
  ];
  plan.entries.forEach((x, i) => {
    lines.push(
      "",
      `${i + 1}. ${x.step} [${x.kind}]`,
      `   Hazard:            ${x.hazard}`,
      `   Critical limit:    ${x.limit}`,
      `   Monitoring:        ${x.monitor}`,
      `   Corrective action: ${x.corrective}`,
      `   Verification:      ${x.verify}`,
      `   Record:            ${x.record}`
    );
  });
  lines.push("", "-".repeat(50), `CCP = ${KIND_MEANING.CCP}`, `CP = ${KIND_MEANING.CP}`, `QCP = ${KIND_MEANING.QCP}`, "", ...plan.notes);
  return lines.join("\n");
}
