/**
 * Food-safety reference layer. Safety-critical answers are RETRIEVED from these
 * curated rules, not generated by the model — the #1 trust requirement. Small
 * and hand-verified; expand deliberately. Sources named for auditability.
 */

export type SafetyRule = { domain: string; kw: string[]; rule: string; source: string };

export const SAFETY_RULES: SafetyRule[] = [
  {
    domain: "brine/cure",
    kw: ["brine", "brined", "cure", "curing", "corned", "pastrami", "prague powder", "pink salt", "nitrite", "saltpeter"],
    rule: "Brine/cure salt (and nitrite) is FUNCTIONAL CHEMISTRY, not seasoning — scale the salt/cure LINEARLY with the water and meat to preserve the exact concentration. NEVER dampen it. Nitrite has strict ppm limits; follow a validated cure calculator.",
    source: "USDA FSIS / NCHFP",
  },
  {
    domain: "pickling/canning",
    kw: ["pickle", "pickling", "canning", "water bath", "shelf stable", "shelf-stable", "preserve", "jam", "acidify"],
    rule: "Preservation acidity is safety-critical — for water-bath canning the product must reach pH < 4.6 (add acid, or pressure-can). Do NOT reduce vinegar/acid for flavor. Use a tested NCHFP recipe.",
    source: "NCHFP",
  },
  {
    domain: "garlic-in-oil",
    kw: ["garlic oil", "garlic-in-oil", "garlic confit", "herb oil", "infused oil"],
    rule: "Garlic/herb in oil is low-acid + anaerobic = botulism risk. Refrigerate <=3-4 days or freeze; never hold at room temperature; commercial storage requires validated acidification.",
    source: "USDA / FDA",
  },
  {
    domain: "sous-vide",
    kw: ["sous vide", "sous-vide", "immersion circulator", "vacuum seal", "reduced oxygen", "rop"],
    rule: "Sous-vide / reduced-oxygen pasteurization time depends on temperature AND thickness AND log-reduction — do NOT improvise a time. Defer to a validated table (Baldwin / USDA).",
    source: "Baldwin / USDA",
  },
  {
    domain: "fermentation",
    kw: ["ferment", "fermented", "kraut", "kimchi", "lacto"],
    rule: "Fermentation salt % is functional (it controls the culture and safety) — hold the exact salt-by-weight ratio; do not dampen. Follow a validated fermentation ratio.",
    source: "NCHFP",
  },
];

/** Canonical hard temps/times — used verbatim, never invented by the model. */
export const HARD_TEMPS = [
  "Safe internal cook temps: poultry/stuffed 165F (15s); ground meat 155F (17s); whole-muscle meat/fish/eggs 145F (15s).",
  "Hot-hold at 135F or above; cold-hold at 41F or below (danger zone 41-135F — minimize time in it).",
  "2-stage cooling: 135->70F within 2 h, then 70->41F within 4 more h (<=6 h total), in SHALLOW pans; reheat to 165F within 2 h.",
];

/** Safety rules whose keywords appear in the recipe text. */
export function detectSafety(text: string): SafetyRule[] {
  const t = (text || "").toLowerCase();
  return SAFETY_RULES.filter((r) => r.kw.some((k) => t.includes(k)));
}

/** True if the recipe is a functional-chemistry prep (do NOT dampen salt/acid). */
export function isFunctionalChemistry(text: string): boolean {
  return detectSafety(text).some((r) => ["brine/cure", "pickling/canning", "fermentation"].includes(r.domain));
}
