/* GENERATED by scripts/build-brain.ts from docs/kitchen-brain/knowledge-pack.v3.0.md — do not edit by hand; run `npm run brain`. */
export const KNOWLEDGE_PACK_VERSION = "3.0";
export const KNOWLEDGE_PACK_TITLE = "Universal Culinary Production Knowledge Pack";
export type KnowledgeSection = { id: string; title: string; body: string };
/** One entry per section of the pack, verbatim. Retrieval lives in ./retrieve.ts. */
export const KNOWLEDGE_SECTIONS: KnowledgeSection[] = [
  {
    "id": "purpose-and-rule-classes",
    "title": "Purpose and rule classes",
    "body": "•  This pack contains universal production mathematics, culinary scaling methods, validation logic, and configurable working assumptions.\n•  Universal formula means mathematically stable across operations.\n•  Working assumption means useful only until a recipe test, product specification, organization rule, or production record replaces it.\n•  Verified value means supported by an approved recipe, product specification, label, test, or production record.\n•  Facility rule and jurisdiction rule belong in overlays, not in the universal pack."
  },
  {
    "id": "core-finished-yield-equations",
    "title": "Core finished yield equations",
    "body": "•  Required finished yield by weight = approved portions × finished weight per portion.\n•  Required finished yield by volume = approved portions × finished volume per portion.\n•  Scale factor = target finished yield ÷ verified baseline finished yield.\n•  Scaled stable ingredient = baseline ingredient × scale factor.\n•  Actual portions = actual finished yield ÷ approved finished portion.\n•  Overage or shortage = actual finished yield − required finished yield.\n•  Portion variance percentage = (actual portion − standard portion) ÷ standard portion × 100."
  },
  {
    "id": "ap-ep-and-process-yield",
    "title": "AP EP and process yield",
    "body": "•  Yield percentage = edible or finished quantity ÷ as-purchased or raw quantity.\n•  Required AP quantity = required EP or finished quantity ÷ yield percentage.\n•  Expected EP or finished quantity = AP or raw quantity × yield percentage.\n•  Trim loss = AP − EP.\n•  Cook loss = raw edible quantity − cooked finished quantity.\n•  Drain yield, thaw loss, bone loss, skin loss, purge, evaporation, absorption, and transfer loss must be modeled separately when material.\n•  Never apply one generic yield percentage across different products, cuts, suppliers, or cooking methods without labeling it an assumption."
  },
  {
    "id": "weight-volume-and-density",
    "title": "Weight volume and density",
    "body": "•  Weight and volume are not interchangeable without density or a verified measured conversion.\n•  Use weight for meats, produce, dry goods, and finished components when portion control depends on mass.\n•  Use volume for broths, beverages, soups, sauces, dressings, mayos, salsas, and liquid condiments when service and purchasing use volume.\n•  Use count for pieces, buns, tortillas, pizzas, pans, skewers, packages, or other discrete units.\n•  For thick or particulate foods, verify that the service utensil delivers both solids and liquid in the intended ratio.\n•  When converting a volume-based source to weight, measure the actual product density instead of using a generic ingredient density."
  },
  {
    "id": "unit-normalization-and-precision",
    "title": "Unit normalization and precision",
    "body": "•  Normalize all source quantities into one internal unit system before calculating.\n•  Retain full calculation precision internally and round once at the final operational step.\n•  1 lb = 16 oz; 1 kg = 1,000 g; 1 US gal = 128 US fl oz; 1 US qt = 32 US fl oz; 1 US cup = 8 US fl oz.\n•  US fluid ounces are volume and ounces are weight; never treat them as equivalent.\n•  Use verified local standards for cups, tablespoons, teaspoons, gallons, and pints because definitions vary by region.\n•  Display kitchen-friendly fractions only after the unrounded total is validated."
  },
  {
    "id": "rounding-hierarchy",
    "title": "Rounding hierarchy",
    "body": "•  Do not round early.\n•  Round pieces, packages, pans, and cuts to whole executable units.\n•  Round purchasing quantities upward only after subtracting usable inventory when inventory use is authorized.\n•  Bulk low-impact ingredients may be rounded for production practicality if the finished yield remains intact.\n•  High-impact ingredients require conservative rounding, test batches, or staged additions.\n•  Show both target yield and actual rounded yield when operational rounding changes the count."
  },
  {
    "id": "high-impact-ingredients",
    "title": "High impact ingredients",
    "body": "•  Review salt, curing agents, chiles, pepper extracts, fish sauce, soy sauce, vinegar, citrus, alcohol, smoke flavor, flavoring oils, sesame oil, extracts, concentrates, bouillon, bases, leaveners, stabilizers, gums, and enzymes independently.\n•  Linear scaling is a starting calculation, not automatic authorization.\n•  Account for concentration, surface area, evaporation, absorption, holding time, carryover seasoning, and repeated sauce applications.\n•  Use staged additions with a documented maximum when sensory testing is required.\n•  Never round a trace extract, cure, chemical leavener, or concentrated additive to a convenient large unit."
  },
  {
    "id": "sub-recipe-dependency-scaling",
    "title": "Sub recipe dependency scaling",
    "body": "•  Calculate the parent recipe’s required finished amount of each sub-recipe.\n•  Divide required sub-recipe output by its verified baseline finished yield to obtain the sub-recipe scale factor.\n•  Round the sub-recipe batch only after identifying equipment minimums, package units, and acceptable overage.\n•  Feed the actual rounded sub-recipe output back into the parent validation.\n•  Consolidate common sub-recipes across menu items only when the formulation and allergen profile are identical.\n•  Prevent the same sub-recipe ingredients from being counted both within the parent and again as a separate requirement."
  },
  {
    "id": "build-reconciliation",
    "title": "Build reconciliation",
    "body": "•  For composed dishes, sum the per-portion components and confirm they equal the stated finished portion.\n•  For bulk mixed dishes, sum expected finished component weights and compare with the stated batch yield.\n•  Document process loss, evaporation, retained cooking liquid, draining, or trim when the totals do not reconcile directly.\n•  For sauces absorbed during holding, distinguish amount produced, amount added, amount retained, and amount served.\n•  For split service, allocate the master batch by location, station, or meal period and prevent duplicate procurement."
  },
  {
    "id": "proteins",
    "title": "Proteins",
    "body": "•  Scale cooked portions from cooked finished yield; convert to raw purchasing quantity using a verified yield for the exact cut and method.\n•  Bone-in, skin-on, trimmed, marinated, injected, breaded, frozen, and precooked products require different yield logic.\n•  For count-based proteins such as shrimp, wings, ribs, or fillets, reconcile average piece weight with portion count.\n•  Account for purge, thaw loss, trim, cooking loss, carryover, slicing loss, and holding loss when material.\n•  Do not use safe minimum temperature as the tenderness endpoint for a braised cut."
  },
  {
    "id": "rice-grains-legumes-and-absorbed-liquids",
    "title": "Rice grains legumes and absorbed liquids",
    "body": "•  Do not confuse dry weight with cooked yield.\n•  Use the verified cooked-yield ratio for the exact product and method. Generic ratios are working assumptions only.\n•  Required dry amount = required cooked amount ÷ verified cooked-yield multiplier.\n•  Separate dry grain, cooking liquid, cooked target, drained target when applicable, and final incorporated amount.\n•  Forecast by finished weight rather than visual pan fullness.\n•  Verify the actual service scoop by weighing multiple normal portions.\n•  For legumes, distinguish dry, soaked, cooked, drained, and liquid-retained weights."
  },
  {
    "id": "pasta-noodles-and-hydration",
    "title": "Pasta noodles and hydration",
    "body": "•  Track dry, fresh, frozen, precooked, soaked, cooked, drained, and finished weights distinctly.\n•  Use an actual yield for the product and doneness standard; generic doubling is only a working assumption.\n•  Account for sauce absorption during holding and avoid treating absorbed sauce as unexplained yield.\n•  Validate that noodle or pasta quantity is meaningful for the menu identity.\n•  Plan shallow holding, staged saucing, or small batches when continued absorption damages quality."
  },
  {
    "id": "vegetables-fruits-and-herbs",
    "title": "Vegetables fruits and herbs",
    "body": "•  Apply trim and cooking yield to the exact form purchased.\n•  Distinguish whole, peeled, seeded, cored, trimmed, drained, thawed, cooked, and finished states.\n•  Leafy herbs and garnishes often require count, bunch, case, or usable-weight conversion verified from the supplier.\n•  Do not reduce a recipe because of an ordering or delivery overage unless production records show actual recipe overuse.\n•  Account for water loss, compression, oxidation, and holding when they materially affect portion or quality."
  },
  {
    "id": "sauces-dressings-soups-and-beverages",
    "title": "Sauces dressings soups and beverages",
    "body": "•  Scale by finished volume or verified finished weight, not by the sum of unprocessed ingredient volumes.\n•  Required volume = portions × volume per portion plus only an approved production allowance.\n•  Account for evaporation, straining, blending expansion, retained solids, absorption, kettle heel, transfer loss, and service residue.\n•  For chunky soups and sauces, verify the intended solids-to-liquid ratio and utensil delivery.\n•  A slurry, roux, reduction, puree, starch, gum, or emulsion must be based on the tested final texture rather than added automatically.\n•  For beverages and concentrates, use the manufacturer dilution ratio unless an approved tested formulation replaces it."
  },
  {
    "id": "baking-dough-and-portioned-products",
    "title": "Baking dough and portioned products",
    "body": "•  Baker’s percentage expresses each ingredient as a percentage of flour weight; total dough weight must still reconcile to piece count.\n•  Dough required = pieces or pans × dough weight per piece or pan.\n•  Account for divider loss, bowl residue, proofing limits, bake loss, icing, filling, and finishing yield.\n•  Pan size, piece weight, proofing method, bake profile, and cut count are required for reproducible scaling.\n•  Frozen preformed or pre-sheeted products follow verified piece count and package specifications rather than scratch dough assumptions."
  },
  {
    "id": "pans-vessels-packages-and-equipment-capacity",
    "title": "Pans vessels packages and equipment capacity",
    "body": "•  Required containers = required finished quantity ÷ approved usable quantity per container, rounded to a whole container.\n•  Never use nominal vessel capacity as safe working capacity.\n•  Respect maximum fill depth, headspace, circulation, rack loading, recovery time, mixing limits, and safe handling weight.\n•  Divide batches so each batch uses the same formulation ratio and receives consistent cook, cool, and hold treatment.\n•  Package ordering and recipe use are separate: purchasing may round to a case while production uses only the approved amount."
  },
  {
    "id": "cut-count-and-discrete-yield",
    "title": "Cut count and discrete yield",
    "body": "•  Required whole items = target portions ÷ portions per whole item, rounded up.\n•  Actual portions = rounded whole items × portions per whole item.\n•  Use this logic for pizzas, cakes, sandwiches cut into portions, sheet pans, loaves, packages, skewers, and similar items.\n•  State the whole-item count, cut count, target count, and actual count."
  },
  {
    "id": "batch-sequencing-holding-and-replenishment",
    "title": "Batch sequencing holding and replenishment",
    "body": "•  A scaled recipe must specify whether the full quantity is produced at once or in controlled batches.\n•  Model cook time, recovery time, cooling capacity, holding duration, transport, service rate, and replenishment frequency.\n•  Crispy foods generally require ventilation and late finishing; starches and noodles may absorb liquid; emulsions may break; vegetables may continue cooking.\n•  Quality limits may require smaller batches even when equipment can hold the full volume.\n•  Food-safety limits must come from the configured jurisdiction and approved organizational policy."
  },
  {
    "id": "procurement-consolidation",
    "title": "Procurement consolidation",
    "body": "•  Convert each recipe requirement to a common purchasing unit only after recipe validation.\n•  Consolidate identical products across recipes; do not consolidate products with different specifications or allergen profiles.\n•  Separate exact usable demand, authorized inventory deduction, purchase requirement, case pack, cases ordered, and expected remainder.\n•  Do not invent case packs or supplier yields.\n•  Keep fresh, frozen, refrigerated, dry, chemical, specialty, and venue-specific order streams separate when the organization requires it."
  },
  {
    "id": "forecasting-with-production-records",
    "title": "Forecasting with production records",
    "body": "•  Forecast from comparable events, venue traffic, menu role, station take rate, weather, calendar, price, audience, and service duration when data exists.\n•  Record planned portions, actual production, portions served, leftovers, waste, transfers, sell-outs, and substitutions.\n•  Adjusted forecast is a decision, not a recipe change.\n•  Update a recipe yield only when the formulation or verified production yield changed.\n•  Preserve event context so a one-time anomaly is not generalized worldwide."
  },
  {
    "id": "validation-tests-before-release",
    "title": "Validation tests before release",
    "body": "•  Count × portion equals target finished yield.\n•  Component build equals finished portion.\n•  Baseline yield is finished yield, not ingredient total.\n•  Raw purchasing quantity supports the cooked requirement.\n•  All sub-recipes are present and scaled once.\n•  High-impact ingredients received independent review.\n•  Batch and vessel capacities are executable.\n•  Target and actual rounded yield are visible.\n•  Recipe, prep, and procurement totals agree.\n•  Units, locale, regulatory status, allergens, and verification flags are complete."
  }
];
