/**
 * Generates the engine's brain modules from the governing documents:
 *
 *   docs/kitchen-brain/current.json  →  lib/engine/brain/master-prompt.ts
 *                                       lib/engine/brain/knowledge-pack.ts
 *
 * The documents are stored verbatim as markdown (see docs/kitchen-brain/README.md);
 * the version each reports comes from its own header table (`| Version | 3.0 |`).
 *
 *   npm run brain
 */
import fs from "node:fs";
import path from "node:path";

const DOCS = path.resolve(process.cwd(), "docs", "kitchen-brain");
const OUT = path.resolve(process.cwd(), "lib", "engine", "brain");

type Current = { masterPrompt: string; knowledgePack: string };
const current = JSON.parse(fs.readFileSync(path.join(DOCS, "current.json"), "utf8")) as Current;

function readDoc(file: string) {
  const md = fs.readFileSync(path.join(DOCS, file), "utf8").replace(/\r\n/g, "\n").trim();
  const title = (md.match(/^# (.+)$/m)?.[1] || file).trim();
  const version = (md.match(/^\|\s*Version\s*\|\s*([^|]+)\|/m)?.[1] || "unversioned").trim();
  return { md, title, version };
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/** One entry per H1 section. The first H1 block (title, subtitle, version table) is front matter. */
function sections(md: string) {
  const blocks = md.split(/^(?=# )/m).map((b) => b.trim()).filter(Boolean);
  const out: { id: string; title: string; body: string }[] = [];
  for (const block of blocks.slice(1)) {
    const m = block.match(/^# (.+)\n([\s\S]*)$/);
    if (!m) continue;
    out.push({ id: slug(m[1]), title: m[1].trim(), body: m[2].trim() });
  }
  return out;
}

const banner = (src: string) =>
  `/* GENERATED by scripts/build-brain.ts from docs/kitchen-brain/${src} — do not edit by hand; run \`npm run brain\`. */\n`;

fs.mkdirSync(OUT, { recursive: true });

const mp = readDoc(current.masterPrompt);
fs.writeFileSync(
  path.join(OUT, "master-prompt.ts"),
  banner(current.masterPrompt) +
    `export const MASTER_PROMPT_VERSION = ${JSON.stringify(mp.version)};\n` +
    `export const MASTER_PROMPT_TITLE = ${JSON.stringify(mp.title)};\n` +
    `/** The governing document, verbatim (markdown). */\n` +
    `export const MASTER_PROMPT = ${JSON.stringify(mp.md)};\n`
);

const kp = readDoc(current.knowledgePack);
const secs = sections(kp.md);
fs.writeFileSync(
  path.join(OUT, "knowledge-pack.ts"),
  banner(current.knowledgePack) +
    `export const KNOWLEDGE_PACK_VERSION = ${JSON.stringify(kp.version)};\n` +
    `export const KNOWLEDGE_PACK_TITLE = ${JSON.stringify(kp.title)};\n` +
    `export type KnowledgeSection = { id: string; title: string; body: string };\n` +
    `/** One entry per section of the pack, verbatim. Retrieval lives in ./retrieve.ts. */\n` +
    `export const KNOWLEDGE_SECTIONS: KnowledgeSection[] = ${JSON.stringify(secs, null, 2)};\n`
);

console.log(`master prompt  ${mp.title} v${mp.version}  (${mp.md.split(/\s+/).length} words)`);
console.log(`knowledge pack ${kp.title} v${kp.version}  (${secs.length} sections, ${kp.md.split(/\s+/).length} words)`);
for (const s of secs) console.log(`  - ${s.id}`);
